In [3]:
import tensorflow as tf
import numpy as np
from termcolor import colored

In [4]:
print(('Your TensorFlow version: {0}').format(tf.__version__))

Your TensorFlow version: 2.3.0


# **simple numerical example for feed forward**

In [5]:
n_input=4
n_hidden1=3
n_hidden2=3
n_output=2

weights = {
    'w1': tf.Variable(tf.random.truncated_normal([n_input, n_hidden1], stddev=0.1)),
    'w2': tf.Variable(tf.random.truncated_normal([n_hidden1, n_hidden2], stddev=0.1)),
    'out': tf.Variable(tf.random.truncated_normal([n_hidden2, n_output], stddev=0.1)),
}
biases = {
    'b1': tf.Variable(tf.constant(0.1, shape=[n_hidden1])),
    'b2': tf.Variable(tf.constant(0.1, shape=[n_hidden2])),
    'out': tf.Variable(tf.constant(0.1, shape=[n_output]))
}

In [6]:
weights['w1'].shape

TensorShape([4, 3])

In [7]:
weights['w2'].shape

TensorShape([3, 3])

In [8]:
biases['out'].shape

TensorShape([2])

In [9]:
weights['out'].shape

TensorShape([3, 2])

In [10]:
x=tf.Variable([[1.0, 2.0, 3.0,4.0], [4.0, 5.0, 6.0,7.0],[7.0,8.0,9.0,10.0]])
output=tf.Variable([[1.0, 2.0], [4.0, 5.0],[6.0,5.0]])

In [11]:
output.shape

TensorShape([3, 2])

In [12]:

hidden_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['w1']),biases['b1']))  # hidden value calc
hidden_2 = tf.nn.sigmoid(tf.add(tf.matmul(hidden_1, weights['w2']),biases['b2']))
y_hat = tf.tanh(tf.add(tf.matmul(hidden_2,weights['out']),biases['out'])) 

In [13]:
y_hat

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.10159659, 0.11569624],
       [0.10164171, 0.11499551],
       [0.10168087, 0.11437882]], dtype=float32)>

In [14]:
cce = tf.keras.losses.CategoricalCrossentropy()

In [15]:
cce(y_hat, output).numpy()

0.15345281

In [16]:
mse = tf.keras.losses.MeanSquaredError(reduction=tf.keras.losses.Reduction.SUM)

In [17]:
mse(output, y_hat).numpy()

51.03883

In [18]:
tf.nn.sigmoid((1*0.3) + (1*0.4) +(0*0.5) +(0*0.5)+0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.76852477>

In [19]:
output=tf.Variable([[1.0,0.0]])

In [20]:
y_hat=tf.Variable([[0.8037,0.1097]])

In [21]:
mse = tf.keras.losses.MeanSquaredError()
mse(output, y_hat).numpy()

0.025283895

In [ ]:
tf.keras.