In [1]:
import tensorflow as tf

In [3]:
print('your tensorflow version: {}'.format(tf.__version__))

your tensorflow version: 2.3.0


In [21]:
# scalar: a scaler has magnitude(size) only
x=tf.constant(3)
print('scalar',x)
# vector: a vector has both magnitude(size) and direction 
x=tf.constant([2,3,4,5])
print('vector',x)
# matrix
x=tf.constant([[2,3,5],[5,6,7]])
print('matrix',x)
# tensor
x=tf.constant([[7,7,8],[8,7,8],[8,8,9]])
print('tensor',x)

scalar tf.Tensor(3, shape=(), dtype=int32)
vector tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
matrix tf.Tensor(
[[2 3 5]
 [5 6 7]], shape=(2, 3), dtype=int32)
tensor tf.Tensor(
[[7 7 8]
 [8 7 8]
 [8 8 9]], shape=(3, 3), dtype=int32)


In [32]:
# stacking
a=tf.constant(3)
print(a)
b=tf.stack([a,a])
print(b)
c=tf.stack([b,b])
print(c)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(
[[3 3]
 [3 3]], shape=(2, 2), dtype=int32)


In [34]:
#slicing
a=tf.constant([[1,2,3],[4,5,6]])
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [44]:
slic_a=a[:,1]
print(slic_a)

tf.Tensor([2 5], shape=(2,), dtype=int32)


In [ ]:
# variable
var=tf.Variable()