In [1]:
import tensorflow as tf
from termcolor import colored

In [2]:
print(('Your TensorFlow version: {0}').format(tf.__version__))

Your TensorFlow version: 2.3.0


# **Using GPU  and CPU IN tensorflow**

In [3]:

import time

cpu_slot = 0
gpu_slot = 0

# Using CPU at slot 0
with tf.device('/CPU:' + str(cpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    B= tf.constant([[3, 2], [5, 2]])
    print(A+B)

    # Printing how long it took with CPU
    end = time.time() - start
    print(" using cpu",end)
    print("\n")

# Using the GPU at slot 0
with tf.device('/GPU:' + str(gpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    B= tf.constant([[3, 2], [5, 2]])
    print(A+B)

    # Printing how long it took with CPU
    end = time.time() - start
    print("using Gpu",end)

tf.Tensor(
[[ 6  4]
 [10  4]], shape=(2, 2), dtype=int32)
 using cpu 0.34428906440734863


tf.Tensor(
[[ 6  4]
 [10  4]], shape=(2, 2), dtype=int32)
using Gpu 0.0009586811065673828


TensorFlow programs use a data structure called tensor to represent all the data. Any type of data you plan to use for your model can be stored in Tensors. Simply put, a Tensor is a multi-dimensional array (0-D tensor: scalar, 1-D tensor: vector, 2-D tensor: matrix, and so on). Hence, TensorFlow is simply referring to the flow of the Tensors in the computational graph.


Tensor is multi dimensional array

A scalar is rank_0_tensor

A vector is rank_1_tensor

A matrix is rank_2_tensor 


**Scalar**

In [4]:
x=tf.constant(3.0)
print(x)

tf.Tensor(3.0, shape=(), dtype=float32)


**Vector**

In [5]:
x=tf.constant([3,5,7])
print(x)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)


**Matrix**

In [6]:
x=tf.constant([[3,5,7],[3,5,7]])
print(x)

tf.Tensor(
[[3 5 7]
 [3 5 7]], shape=(2, 3), dtype=int32)


**Tensor**

In [7]:
x=tf.constant([[3,5,7],[3,5,7],[3,5,7]])
print(x)

tf.Tensor(
[[3 5 7]
 [3 5 7]
 [3 5 7]], shape=(3, 3), dtype=int32)


**Stacking**

In [8]:
a=tf.constant(3)
print(a)

tf.Tensor(3, shape=(), dtype=int32)


In [9]:
b=tf.stack([a,a])
print(b)

tf.Tensor([3 3], shape=(2,), dtype=int32)


In [10]:
c=tf.stack([b,b])
print(c)

tf.Tensor(
[[3 3]
 [3 3]], shape=(2, 2), dtype=int32)


**Slicing**

In [11]:
a=tf.constant([[1,2,3],[4,5,6]])
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [12]:
sliced_a=a[:,1]
print(sliced_a)

tf.Tensor([2 5], shape=(2,), dtype=int32)


In [13]:
sliced_b=a[1,:]
print(sliced_b)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


**Reshaping**

In [14]:
reshaped_a=tf.reshape(a,[3,2])
print(reshaped_a)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


**Variable**

In [15]:
var=tf.Variable([2,3],dtype=tf.int32,name='var')
print(var)

<tf.Variable 'var:0' shape=(2,) dtype=int32, numpy=array([2, 3])>


In [16]:
print("Shape: ",var.shape)
print("DType: ",var.dtype)
print("As NumPy: ",var.numpy)

Shape:  (2,)
DType:  <dtype: 'int32'>
As NumPy:  <bound method BaseResourceVariable.numpy of <tf.Variable 'var:0' shape=(2,) dtype=int32, numpy=array([2, 3])>>


In [17]:
var_add=var.assign_add([3,4])
print(var_add)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 7])>


In [18]:
var_sub=var_add.assign_sub([1,1])
print(var_sub)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 6])>


**Operations**

In [19]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

b= tf.constant([[1, 2],
                 [3, 4]])

print(b)

print(colored("Addition\n","blue"),a+b)# all other operations
print(colored("element wise multiplication\n", "blue"),a*b) # element-wise multiplication
print(colored("matrix multiplication\n", "blue"),a @b ) # matrix multiplication

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Addition
 tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
element wise multiplication
 tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
matrix multiplication
 tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


Other useful Operations

In [20]:
c = tf.constant([[1.0, 2.0],
                 [3.0, 2.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[0.26894143 0.7310586 ]
 [0.7310586  0.26894143]], shape=(2, 2), dtype=float32)


**zeros**

In [21]:
tf.zeros(shape=[3, 3], dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

**ones**

In [22]:
 tf.ones(shape=[3, 3], dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

**Cast types**

In [23]:
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

**Function**

In [24]:


# Define a Python function
def function_to_get_faster(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# Create a `Function` object that contains a graph
a_function_that_uses_a_graph = tf.function(function_to_get_faster)

# Make some tensors
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

# It just works!
a_function_that_uses_a_graph(x1, y1, b1)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

In [25]:
print(x1)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)


In [26]:
print(y1)

tf.Tensor(
[[2.]
 [3.]], shape=(2, 1), dtype=float32)


In [27]:
print(b1)

tf.Tensor(4.0, shape=(), dtype=float32)


**Graph**

Graphs are data structures that contain a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations.




The way you create a graph in TensorFlow is to use tf.function, either as a direct call or as a decorator.

In [28]:
# Don't read the output too carefully.
print(tf.autograph.to_code(function_to_get_faster))

def tf__function_to_get_faster(x, y, b):
    with ag__.FunctionScope('function_to_get_faster', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        x = ag__.converted_call(ag__.ld(tf).matmul, (ag__.ld(x), ag__.ld(y)), None, fscope)
        x = (ag__.ld(x) + ag__.ld(b))
        try:
            do_return = True
            retval_ = ag__.ld(x)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



**Feed Forward**

In [29]:
W = tf.Variable(tf.ones(shape=(2,2)), name="W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")

@tf.function
def forward(x):
  return W * x + b

out_a = forward([1,0])
print(out_a)

tf.Tensor(
[[1. 0.]
 [1. 0.]], shape=(2, 2), dtype=float32)


In [30]:
W

<tf.Variable 'W:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [31]:
b

<tf.Variable 'b:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [32]:
out_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.]], dtype=float32)>