In [1]:
docs=["the train leaves every morning at 7 AM",
    "i had not been cooking any breakfast when my mom is in home",
     "again the arrives at 7 PM every evening"]

# count vectorizer

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')

In [3]:
countvect=cv.fit_transform(docs)

In [4]:
print(cv.vocabulary_)

{'train': 9, 'leaves': 5, 'morning': 7, 'cooking': 2, 'breakfast': 1, 'mom': 6, 'home': 4, 'arrives': 0, 'pm': 8, 'evening': 3}


In [5]:
countvect.shape

(3, 10)

In [6]:
countvect.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0]], dtype=int64)

## TFIDF_Transformer

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer
tt=TfidfTransformer()

In [8]:
tt.fit(countvect)

TfidfTransformer()

In [9]:
tfidf_transformer=tt.transform(countvect)

In [10]:
tfidf_transformer

<3x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [11]:
tfidf_transformer.shape

(3, 10)

In [12]:
tfidf_transformer.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.        , 0.5       , 0.5       , 0.        , 0.5       ,
        0.        , 0.5       , 0.        , 0.        , 0.        ],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.        ]])

#  TFIDF VECTORIZER

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer()

In [14]:
tfidf_vector=tv.fit_transform(docs)

In [15]:
tfidf_vector

<3x23 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [16]:
tfidf_vector.shape

(3, 23)

In [17]:
tfidf_vector.toarray()

array([[0.        , 0.41756662, 0.        , 0.        , 0.31757018,
        0.        , 0.        , 0.        , 0.        , 0.31757018,
        0.        , 0.        , 0.        , 0.        , 0.41756662,
        0.        , 0.41756662, 0.        , 0.        , 0.        ,
        0.31757018, 0.41756662, 0.        ],
       [0.        , 0.        , 0.28867513, 0.        , 0.        ,
        0.28867513, 0.28867513, 0.28867513, 0.        , 0.        ,
        0.28867513, 0.28867513, 0.28867513, 0.28867513, 0.        ,
        0.28867513, 0.        , 0.28867513, 0.28867513, 0.        ,
        0.        , 0.        , 0.28867513],
       [0.41756662, 0.        , 0.        , 0.41756662, 0.31757018,
        0.        , 0.        , 0.        , 0.41756662, 0.31757018,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.41756662,
        0.31757018, 0.        , 0.        ]])